name: smogix
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # Core Python + data stack
  - python=3.9
  - numpy=1.23.5
  - pandas=1.3.2
  - scipy=1.7.1
  - scikit-learn=0.24.2
  - matplotlib=3.4.3
  - protobuf=3.20.3

  # GPU-enabled PyTorch (bundles CUDA runtime)
  - pytorch=2.2.2
  - torchvision=0.17.2
  - torchaudio=2.2.2
  - pytorch-cuda=11.8

  # Optional CLI tools
  - pip

  # Pip-only packages
  - pip:
      - absl-py==0.13.0
      - backcall==0.2.0
      - cachetools==4.2.2
      - charset-normalizer==2.0.4
      - chumpy==0.70
      - cycler==0.10.0
      - decorator==5.0.9
      - google-auth==1.35.0
      - google-auth-oauthlib==0.4.5
      - grpcio==1.39.0
      - idna==3.2
      - imageio==2.9.0
      - ipdb==0.13.9
      - ipython==7.26.0
      - ipython-genutils==0.2.0
      - jedi==0.18.0
      - joblib==1.0.1
      - kiwisolver==1.3.1
      - markdown==3.3.4
      - matplotlib-inline==0.1.2
      - oauthlib==3.1.1
      - python-dateutil==2.8.2
      - pytz==2021.1
      - pyyaml==5.4.1
      - requests==2.26.0
      - requests-oauthlib==1.3.0
      - rsa==4.7.2
      - smplx==0.1.28
      - tensorboard==2.6.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.0
      - threadpoolctl==2.2.0
      - toml==0.10.2
      - tqdm==4.62.2
      - traitlets==5.0.5
      - urllib3==1.26.6
      - wcwidth==0.2.5
      - werkzeug==2.0.1
      - git+https://github.com/openai/CLIP.git
      - git+https://github.com/nghorbani/human_body_prior
      - gdown
